function SmithChart = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  SMITHCHART = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the numeric data.
%
%  SMITHCHART = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  SmithChart = importfile("C:\Users\Vittorio De Lauso\Desktop\1Q\Aero engine\Assignments\A2\Smith_Chart.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 21-Oct-2022 14:37:28

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "VarName3"];
opts.VariableTypes = ["double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
SmithChart = readtable(filename, opts);

%% Convert to output type
SmithChart = table2array(SmithChart);
end